### ISSUE TITLE
Hombridge crashed while diming Tridonic bDW (PWM/2ch/Dim)

### ISSUE THREAD

**Issue by murksel** [awahlig/homebridge-casambi#23]
Homebridge crashed while diming Tridonic device 
Here is the log:

> [24/01/2022, 17:46:58] [Casambi] Successfully logged in to Casambi network Elbstr
> [24/01/2022, 17:46:59] [Casambi] Found 3 unit(s) in the network Elbstr
> [24/01/2022, 17:46:59] [Casambi] Unit Elbblick fluter  is a Luminaire with fixtureId 8616
> [24/01/2022, 17:46:59] [Casambi] Restoring accessory Elbblick fluter 
> [24/01/2022, 17:46:59] [Casambi] Unit Küche is a BatterySwitch with fixtureId 200001
> [24/01/2022, 17:46:59] [Casambi] Skipping unit Küche - unsupported type BatterySwitch
> [24/01/2022, 17:46:59] [Casambi] Unit Flur oben is a Driver with fixtureId 8372
> [24/01/2022, 17:46:59] [Casambi] Restoring accessory Flur oben
> [24/01/2022, 17:46:59] [Casambi] Connection successful
> [24/01/2022, 17:47:34] Error: This callback function has already been called by someone else; it can only be called one time.
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
>     at /usr/local/lib/node_modules/homebridge-casambi/src/luminaire.ts:266:21
> [24/01/2022, 17:47:34] Got SIGTERM, shutting down Homebridge...
> [24/01/2022, 17:47:34] [Homebridge UI] Failed to get characteristics for Elbblick fluter  with iid 11: read ECONNRESET
> [24/01/2022, 17:47:39] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
> [24/01/2022, 17:47:44] [HB Supervisor] Restarting Homebridge...

**Comment by awahlig** [comment]
Thanks for reporting. I added a fix and made a new version (0.3.4).
