### ISSUE TITLE
Casambi Plugin Error

### ISSUE THREAD

**Issue by MarkP63** [awahlig/homebridge-casambi#27]
Lights stopped working with HK/HB..  Not sure why. Log shows first error as “Wrong credentials” ? I haven’t knowing change so any ideas?  What produces this error message? Casambi Account login credentials? API key ?  Thanks

**Comment by hellqvio86** [comment]
Your api key needs to be renewed every six months, it's probably that. Mail support@casambi.com and ask them to renew the api key

**Comment by MarkP63** [comment]
Thanks - that was it but I have complained to Casambi as no warning, countdown or automatic renewal. Not good as now have to rebuild Network scenes automations etc.
