### ISSUE TITLE
Can‘t controlle

### ISSUE THREAD

**Issue by ctonina** [awahlig/homebridge-casambi#8]
Hi, 

since yesterday i can‘t controll my lights in homekit with homebrige.

i see the buttons in the system, i can tap it but the lights remain off.

any ideas?

**Comment by awahlig** [comment]
Check the Homebridge log to see if the plugin is logging into the Casambi Cloud API. If it is then the problem most likely is with the Gateway device. If you're using a phone as a Gateway, make sure that the Casambi app is running on it and that you can control the lights from it. Sometimes restarting the app can also help.
